name: Code Checks

on:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  code-checks:
    name: Code Checks
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Install Dependencies
      run: bun install
    - name: ESLint And TSC
      run: bun run lint
    - name: TypeDoc
      run: bun run docs
    - name: Upload TypeDoc
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./out/
  deploy:
    name: Deploy Documentation
    needs: code-checks
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2
